version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.0
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
          name: Building XC
          command: go build -o xc cmd/xc/main.go
      - store_artifacts:
          path: /tmp/build/xc
